### PR TITLE
feat: expose audio context

### LINKED ISSUE #66: Expose AudioContext
Hi,

I'm using Crunker in a small rhythm game prototype; I need the current playback time which you can normally get from `AudioContext.prototype.getOutputTimestamp`, but I'm unable to do this since Crunker isn't exposing the audioContext.

Is it possible to expose this, or against the design philosophy?

### PR DESCRIPTION
**Pull request by lmiller1990**
resolves https://github.com/jackedgson/crunker/issues/66

`yarn test` isn't working for me; is this supposed to run?

I named it `context` to match the `_context` variable. An alternative name might be `audioContext`.

### CODE REVIEW

**Comment by jaggad** [comment]
Screen Shot 2022-01-28 at 2 41 58 pm
Screen Shot 2022-01-28 at 2 42 11 pm

Hmm... tests were working, not sure when they stopped. Let me check this out now.

**Comment by jaggad** [comment]
I've fixed the tests on master, can you please sync and we'll re-run the pipeline.

**Comment by lmiller1990** [comment]
Done!

**Comment by jaggad** [comment]
@lmiller1990 Sorry should have mentioned this before, just one last thing. Can you please update the README with the new getter function documented. Will mergeonce this is complete.

**Comment by lmiller1990** [comment]
Done.

**Review by davwheat — APPROVED** [review]

**Pull request merged**
