### PR TITLE
Added examples

### PR DESCRIPTION
**Pull request by Alynva**
Yesterday I've created two examples to help a guy and think that would be useful add them in the repo.

I used the [gitcdn](https://gitcdn.xyz) to host the live demos. The links in the README doesn't work yet because they point to jackedgson/crunker , wich doesn't have the examples. They do work from my fork:

* [Audio from Client](https://gitcdn.xyz/repo/Alynva/crunker/master/examples/client/index.html)
* [Audio from Server](https://gitcdn.xyz/repo/Alynva/crunker/master/examples/server/index.html)

### CODE REVIEW

**Comment by jaggad** [comment]
@Alynva thanks bro, wondering if we should expose something like a doTheWork method in the core api as a more abstract method which is like the simplest entry point to the API to make simple use cases even simpler.

Will approve this and merge so gitcdn works. However what are.your thoughts on this new abstract method?

Then paramus can ba passed into a single function to generate the output. Could also be redundant and causing confusion.

**Comment by Alynva** [comment]
I think that will be cool, with a well defined schema. Things like 'autoDownload' may not what some users want by default.

But aside as that, the little line that I did the get the buffers from the audio files, that would be awesome have abstracted.

**Comment by jaggad** [comment]
Cool, if you want to take this on let me know. Pretty packed at the moment so if you'd like to I'd appreciate it. 

If not all good, I'll try and implement within the next few weeks. Thanks for all your contributions thusfar. If you'd like to add a contributors section to the readme with your profile, feel free to do so 😎

**Comment by Alynva** [comment]
I probablly can take some effort on that in this week, I'll "`doSomeWork`" in a branch and we talk about it later

**Pull request merged**
