### PR TITLE
add sliceAudio & fix package.json

### PR DESCRIPTION
**Pull request by 27medkamal**
Would be helpful to have this method. I also found an issue with one of the recent commits in `package.json` which should be fixed by this PR as well

### CODE REVIEW

**Review by davwheat — CHANGES_REQUESTED** [review]
We need to implement tests for a new method. Could you do this?

**Comment by 27medkamal** [comment]
Done

**Review by davwheat — APPROVED** [review]

**Comment by 27medkamal** [comment]
Thanks for the merge. Will this be added to a release soon? Thanks.

**Comment by davwheat** [comment]
I don't have release permissions for this package, so you'd need to ask @jaggad about that. :)

**Comment by jaggad** [comment]
Sorry for the delay @davwheat @27medkamal but this is released now.

Note: Deleted previous message from work account for privacy reasons.

**Pull request merged**
